### ISSUE TITLE
Flutter SDK 登录认证在windows端无法使用

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/cloudbase-framework#107]
参考文档：
https://docs.cloudbase.net/quick-start/flutter.html#di-5-bu-chu-shi-hua-huan-jing-bing-diao-yong-ni-ming-deng-lu

代码演示：
```
  // 初始化
  CloudBaseCore core = CloudBaseCore.init({
    'env': 'livewallpaper-0sikk',
    // 填写您的移动应用安全来源凭证
    // 生成凭证的应用标识必须是 Android 包名或者 iOS BundleID
    'appAccess': {
      // 凭证
      'key': 'flutter',
      // 版本
      'version': 'xxxxx'
    }
  });

 // 获取登录对象
      CloudBaseAuth auth = CloudBaseAuth(core);
      CloudBaseAuthState authState = await auth.getAuthState();
      // 唤起匿名登录
      if (authState == null) {
        await auth.signInAnonymously().then((success) {
          // 登录成功
          print(success);
        }).catchError((err) {
          // 登录失败
          print(err);
        });
      }
```

报错：
```
No implementation found for method getAll on channel plugins.flutter.io/package_info
```

**Comment by DaZiYuan** [comment]
Flutter是全平台的，希望SDK不要区别对待windows和web端

**Comment by shenghanqin** [comment]
@binggg 去年的bug，为啥到现在还没有动静呢？

**Comment by QiaokeliHenku** [comment]
今天的flutter - 腾讯云开发匿名登录 还是相同的问题
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)

**Comment by 1021048313** [comment]
我无法使用auth.getAuthState();，给我报错
`E/flutter ( 5091): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 5091): #0      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:142:86)
E/flutter ( 5091): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:36)
E/flutter ( 5091): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:331:12)
E/flutter ( 5091): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:49)
E/flutter ( 5091): #4      MethodChannelSharedPreferencesStore.getAll (package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:54:22)
E/flutter ( 5091): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:191:57)
E/flutter ( 5091): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:58:19)
E/flutter ( 5091): #7      CloudBaseStore.init (package:cloudbase_core/src/store.dart:12:38)
E/flutter ( 5091): #8      AuthCache.getStore (package:cloudbase_auth/src/cache.dart:48:39)
E/flutter ( 5091): #9      CloudBaseAuth.getAuthState (package:cloudbase_auth/src/index.dart:99:39)
E/flutter ( 5091): #10     main (package:blossom_audio/main.dart:27:8)
E/flutter ( 5091): #11     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 5091): #12     _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 5091): #13     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 5091): #14     _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 5091): #15     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 5091): #16     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 5091): #17     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 5091): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 5091): 
`

**Comment by 1021048313** [comment]
我尝试在cloudbase初始化之前加入
`  WidgetsFlutterBinding.ensureInitialized();`，貌似可以通过登录

**Comment by 1021048313** [comment]
我提交工单问了一下，需要flutter版本2.10.0及以下的，我用2.10.0可以成功登录
