### ISSUE TITLE
执行cloudbase framework:deploy 报文件大小超出15MB

### ISSUE THREAD

**Issue by MrZhaoCn** [TencentCloudBase/cloudbase-framework#119]
CloudBase Framework  info     📦 install plugins
 CloudBase Framework  info     callHooks 'preDeploy' 
 CloudBase Framework  info     🔧 init: client...
 CloudBase Framework  info     npm install
 CloudBase Framework  info     🔧 init: server...
 CloudBase Framework  info     🔨 build: client...
 CloudBase Framework  info     🔨 build: server...
 CloudBase Framework  info     🧬 compile: client...
 CloudBase Framework  info     🧬 compile: server...
Error: /Users/ecool/cloudbase-framework/builds/cloudbase-function-build-1604894248252/next-ssr1604894248254.zip 文件大小超出限制 15 MB
    at SamManager.<anonymous> (/Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:200:23)
    at Generator.next (<anonymous>)
    at /Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:4:12)
    at SamManager.uploadFileViaUrlAndKey (/Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:190:16)
    at SamManager.<anonymous> (/Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:173:28)
    at Generator.next (<anonymous>)
    at /Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:4:12)
    at Promise.all.filesData.map (/Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:172:67)
    at Array.map (<anonymous>)
    at SamManager.<anonymous> (/Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:172:42)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ecool/.nvm/versions/node/v10.15.1/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:5:58)
✖ /Users/ecool/cloudbase-framework/builds/cloudbase-function-build-1604894248252/next-ssr1604894248254.zip 文件大小超出限制 15 MB

rc.json配置如下
{
  "$schema": "https://framework-12561loudbaseapp.com/schema/latest.json",
  "framework": {
    "name": "next-ssr",
    "plugins": {
      "client": {
        "use": "@cloudbase/framework-plugin-next",
        "inputs": {}
      },
      "server": {
        "use": "@cloudbase/framework-plugin-function",
        "inputs": {
          "functionRootPath": "cloudfunctions",
          "functions": [{
            "name": "next-ssr-echo",
            "timeout": 5,
            "envVariables": {},
            "runtime": "Nodejs10.15",
            "memory": 128
          }],
          "servicePaths": {
            "next-ssr-echo": "/next-ssr-echo"
          }
        }
      }
    }
  }
}

**Comment by binggg** [comment]
好的，我们处理下

**Comment by binggg** [comment]
已定位到原因，一方面是egg 插件没有忽略 .next/cache 文件目录，另一方面用户的 public 文件目录包含了过多图片，导致失败

目前采用的方案为 Next export 导出静态来部署
