### ISSUE TITLE
云应用插件错误提示不理想 framework-plugin-container

### ISSUE THREAD

**Issue by shenghanqin** [TencentCloudBase/cloudbase-framework#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

在部署nginx服务器时，nginx.conf的注释方式写错了，正确的为#，但我误写成 // 啦，在部署过程中并没有提醒。后来不得不在本地安装了docker，尝试 docker run 时才发现了问题。

```
server { 
        listen *:80; 
        listen [::]:80; 
        server_name tcb.xiaoxili.com;  // 这里是问题的注释方式     
        location / { 
                 proxy_pass http://static.xiaoxili.com/; 
        } 
} 
```

```plain
正在部署[░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░        ] 80% 600.2 sError: 部署失败，错误信息：[100001]deploy_fail， 请求RequestId：5d28f7fd-b600-4ac0-9466-8e482a71d4ee 
    at SamManager.<anonymous> (/Users/hanqin/.nvm/versions/node/v12.16.2/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:93:35) 
    at Generator.next (<anonymous>) 
    at fulfilled (/Users/hanqin/.nvm/versions/node/v12.16.2/lib/node_modules/@cloudbase/cli/node_modules/@cloudbase/framework-core/lib/sam/index.js:5:58) 
    at runMicrotasks (<anonymous>) 
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 
✖ 部署失败，错误信息：[100001]deploy_fail， 请求RequestId：5d28f7fd-b600-4ac0-9466-8e482a71d4ee 
```

**Screenshots**

![](https://image-hosting.xiaoxili.com/img/20200725155935.png)

![](https://image-hosting.xiaoxili.com/img/20200725155934.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by binggg** [comment]
![image](https://user-images.githubusercontent.com/7686861/90360082-36a4c500-e08d-11ea-9827-14af99461686.png)

已经修复
